### ISSUE TITLE
Create static Press page using new design

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics-pages#6]
### User story
As Loconomics we want our Press page to highlight all the press coverage we've received so that users can use them to vet our credibility and feel more secure about signing up.

#### Tasks
- [x] Create responsive html using Bootstrap 4 and this mockup:
![7 25 18 press](https://user-images.githubusercontent.com/1202838/43800429-1e1b654c-9a45-11e8-8703-d7e0f235ed29.jpg)
- [x] Implement CSS with Loconomics brand colors
- [x] Upload necessary assets

**Comment by joshdanielson** [comment]
@tkwok the png for this page is uploaded already above.

**Comment by tkwok** [comment]
Please provide link to all photos of this mock. Thanks @joshdanielson.

**Comment by joshdanielson** [comment]
@tkwok Christin said those were the images pulled from the link’s metadata. Here’s a blog about it. See if it’s possible?
https://meetedgar.com/blog/facebooks-new-link-previews-need-know-2018/

**Comment by tkwok** [comment]
I'll give this a try and keep you posted @joshdanielson.

**Comment by joshdanielson** [comment]
“A New Wrinkle in the Gig Economy: Workers Get Most of the Money”
By Amy Cortese, New York Times, July 20, 2016
Article URL: http://www.nytimes.com/2016/07/21/business/smallbusiness/a-new-wrinkle-in-the-gig-economy-workers-get-most-of-the-money.html?_r=0
Image URL: https://static01.nyt.com/images/2016/07/21/business/21EBIZ/21EBIZ-articleLarge.jpg

“Platform Cooperativism: contro il modello Uber, motivazioni e sfide di un nuovo mutualismo”
By Elena Taverna, Collaboriamo, March 23, 2016
Article URL: http://www.collaboriamo.org/platform-cooperativism-contro-il-modello-uber-motivazioni-e-sfide-di-un-nuovo-mutualismo/
Image URL: http://www.collaboriamo.org/media/2016/03/own-it-green.png

“These New Co-op Apps Show How to Build Worker Power In the Age of Uber”
By Tom Ladendorf, In These Times, March 21, 2016
Article URL: http://inthesetimes.com/article/18970/labor-rights-to-come-for-uber-and-aribnb-employees
Image URL: http://inthesetimes.com/images/made/images/stocksy_Screen-Shot-2016-03-02-at-7.26.26-PM-copy-2w_850_593.jpg

“4 ways freelancers are disrupting the on-demand economy”
By Laura Murphy, Freelancers Union, November 24, 2015
Article URL: https://blog.freelancersunion.org/2015/11/24/disrupt-on-demand/
Image URL: https://blog.freelancersunion.org/content/images/J1USB78F-1.png

“Get ready for the worker-owned sharing economy”
By Amy Cortese, Cisco's The Network, November 19, 2015
Article URL: https://newsroom.cisco.com/feature-content?type=webcontent&articleId=1727461
Image URL: https://newsroom.cisco.com/documents/10157/14740/next-gen-econ-sharing_1200x630_hero_111915.jpg/f6295d34-1555-45e1-bbc3-1d25ffe54bb1?t=1447890114261

“The True Sharing Economy”
By Zoe Oja Tucker, East Bay Express, November 4, 2015
Article URL: http://www.eastbayexpress.com/oakland/the-true-sharing-economy/Content?oid=4563249
Image URL: https://media2.fdncms.com/eastbayexpress/imager/u/magnum/4563247/mg_feature-1_3804.jpg

“How Platform Coops Can Beat Death Stars Like Uber to Create a Real Sharing Economy”
By Neal Gorenflo, Shareable, November 3, 2015
Article URL: http://www.shareable.net/blog/how-platform-coops-can-beat-death-stars-like-uber-to-create-a-real-sharing-economy
Image URL: https://www.shareable.net/sites/default/files/styles/blog-header-large/public/blog/top-image/ds%20w%20logo.jpg?itok=RkgjOEF_

“The People's Uber: Why The Sharing Economy Must Share Ownership”
By Trebor Scholz and Nathan Schneider, FastCompany CoExist, October 7, 2015
Article URL: http://www.fastcoexist.com/3051845/the-peoples-uber-why-the-sharing-economy-must-share-ownership
Image URL: https://images.fastcompany.net/image/upload/w_596,c_limit,q_auto:best,f_auto/fc/3051845-inline-i-0-the-peoples-uber-why-the-sharing-economy-must-share-ownership.jpg

“The "Sharing Economy" is the Problem”
By Brian Van Slyke and David Morgan, Grassroots Economic Organizing, July 3, 2015
Article URL: http://www.geo.coop/story/sharing-economy-problem
Image URL: http://www.geo.coop/sites/default/files/styles/inline/public/ayn_with_stash_slider_crop.jpg?itok=lvIWYWim

“5 Ways to Take Back Tech”
By Nathan Schneider, The Nation, May 27, 2015
Article URL: http://www.thenation.com/article/5-ways-take-back-tech/
Image URL: https://www.thenation.com/wp-content/uploads/2015/05/uber_computer_rtr_img.jpg?scale=896&compress=80

“Sustaining hierarchy – Uber isn't sharing”
By Francesca Pick and Julia Dreher, Kings Review, May 5, 2015
Article URL: http://kingsreview.co.uk/articles/beyond-hierarchy-why-uber-isnt-part-of-the-sharing-economy/
Image URL: http://kingsreview.co.uk/wp-content/uploads/2015/05/16241406623_45dd03d972_z-1.jpg

“Owning Is the New Sharing”
By Nathan Schneider, Shareable, December 21, 2014
Article URL: http://www.shareable.net/blog/owning-is-the-new-sharing
Image URL: https://www.shareable.net/sites/default/files/styles/blog-header-large/public/blog/top-image/changethemodel.jpg?itok=EqjToIjj

“The collaborative economy is for everyone”
By Juho Makkonen, OuiShare, July 28, 2014
Article URL: (https://www.ouishare.net/article/the-collaborative-economy-is-for-everyone)
Image URL: https://uploads-ssl.webflow.com/5a32b7c449520e00017ffd8b/5ac515d494325d22e0db6d05_Cover%20Copy%2011.jpg

“Cooperatives give new meaning to sharing economy
By Carolyn Said, San Francisco Chronicle, May 24, 2014
Article URL: https://www.sfgate.com/business/article/Cooperatives-give-new-meaning-to-sharing-economy-5502879.php
Image URL: https://s.hdnux.com/photos/30/11/62/6331563/3/920x920.jpg

**Comment by joshdanielson** [comment]
@tkwok some of the images weren't able to be downloaded as I'm assuming there were permission issues. So I listed the src URL for each and the link to the article. Everything you need should be there. Thank you!

**Comment by tkwok** [comment]
No problem @joshdanielson I can create a Loconomics logo as placeholder for these articles that don't have a thumbnail/not allowed due to copyrights.

**Comment by IagoSRL** [comment]
@joshdanielson I implemented the Press page, please review it and let me know any detail.

Some notes:
- I did not implemented pagination for this, all 20 current news are in this single page.
  - I took a look to the pagination options from Hugo but seems would require to add every new as a content file for a new taxonomy, and will generate both the paginated index pages and single page for every new, something not expected here since are just external links
  - I checked the 'data files driven templates' docs too, and "seems" (I may be wrong) pagination doesn't apply to list of items from a data file.
  - Didn't go too further with Hugo on this to get this quicker (and depending on future CMS may be worth it or not the time spent).
  - In case we need to paginate this now, we can just split this in two static pages manually picking the news on each one, adding the pagination buttons at bottom. Or help from anyone knowing how to automate it in Hugo (again, if is quick / worth it).
- On the other side, on this page I did separation of content and template since is a case that had immediate benefits (faster than the other way), so at the `/content/press.html` file rather than html with content you can find just the data for news, just edit, remove or add new ones following current code and correct indentation (above the news there is a couple of comments too).
- I downloaded all images for the news and placed it under a press folder.
- Added a tool to optimize the Press images (could be set-up for others) since there are a lot here I though makes sense (at home page I did it manually)
  - Got confused again with the Hugo tool for this task and couldn't use it. But even better because my final choose can be used out of Hugo without taking too much time.
  - Tried some out-of-the-box tools for this like imagesmin, compress-images but with just around 0.1MB reduction I discard them.
  - Finally I added a custom but still simple tool for this, helped by the `sharp` npm module, got a reduction of size from a 2.36MB total to 1.56MB (-0.8MB). Not as much as expected, but for the whole page load it matters. Doesn't work for SVG but a module named `svgo` on npm could be used when needed.
- All JPEG images compressed with the 'progressive' option enabled, plus the CSS used reserves the image box size without needing the image to compute it so the page seems to load quicker and without content flickering/moving.
- Layout: first new on the page (last by date) takes full width rather than two column as in design, while if the last row of items contains just one item rather than two, that will take full width same as first, because how Flexbox worked there (BTW, I'm using more flexbox CSS directly than BS grid classes, it's making lot of things easier).
  - Can add some additional size restriction to prevent it but doesn't look bad I think (specially having that new and photo there).
  - If you want to promote a different new at the top, just put it first in the list at the `/content/press.html` file

I think that's all, ready for Q/A. As usual, let me know how it works.

**Comment by joshdanielson** [comment]
@iagosrl thank you, will review tonight!

I uploaded content on the home and about pages. Needs some refining but need to think how. Will comment on those tonight.

**Comment by joshdanielson** [comment]
@IagoSRL all looks fantastic! I did the following tests:
- [x] checked images that they matched article
- [x] click on urls and tested they work
- [x] checked author, title, and publication

I made some revisions and am pushing now and closing.
